
target "Example" do
  platform :ios, "9.0"

  pod "GHUITable", :path => "../../GHUITable/"

  pod "GHKit", :path => "~/Projects/GHKit"
  pod "ObjectiveSugar"

  pod "AFNetworking"
  pod "YapDatabase"
  pod "YOLayout"
  pod "SDWebImage"
end
