
target "Example" do
  platform :ios, "8.0"

  pod "GHUITable", :path => "../../GHUITable/"

  pod "GHKit"
  pod "ObjectiveSugar"

  pod "AFNetworking"
  pod "YapDatabase"
  pod "YOLayout"
  pod "SDWebImage"
end
